// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package hexalog is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	Entry
	RPCRequest
	RequestOptions
	RPCResponse
*/
package hexalog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hexaring "github.com/hexablock/hexaring"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	Previous  []byte `protobuf:"bytes,1,opt,name=Previous,json=previous,proto3" json:"Previous,omitempty"`
	Timestamp uint64 `protobuf:"varint,2,opt,name=Timestamp,json=timestamp" json:"Timestamp,omitempty"`
	Height    uint32 `protobuf:"varint,3,opt,name=Height,json=height" json:"Height,omitempty"`
	Key       []byte `protobuf:"bytes,4,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	Data      []byte `protobuf:"bytes,5,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *Entry) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Entry) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Entry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Entry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RPCRequest struct {
	ID      []byte          `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Entry   *Entry          `protobuf:"bytes,2,opt,name=Entry,json=entry" json:"Entry,omitempty"`
	Options *RequestOptions `protobuf:"bytes,3,opt,name=Options,json=options" json:"Options,omitempty"`
}

func (m *RPCRequest) Reset()                    { *m = RPCRequest{} }
func (m *RPCRequest) String() string            { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()               {}
func (*RPCRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RPCRequest) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *RPCRequest) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *RPCRequest) GetOptions() *RequestOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type RequestOptions struct {
	// Index of the source in the PeerSet.  This is set internally by the log
	SourceIndex int32 `protobuf:"varint,1,opt,name=SourceIndex,json=sourceIndex" json:"SourceIndex,omitempty"`
	// Set of peers for the request.
	PeerSet []*hexaring.Location `protobuf:"bytes,2,rep,name=PeerSet,json=peerSet" json:"PeerSet,omitempty"`
}

func (m *RequestOptions) Reset()                    { *m = RequestOptions{} }
func (m *RequestOptions) String() string            { return proto.CompactTextString(m) }
func (*RequestOptions) ProtoMessage()               {}
func (*RequestOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestOptions) GetSourceIndex() int32 {
	if m != nil {
		return m.SourceIndex
	}
	return 0
}

func (m *RequestOptions) GetPeerSet() []*hexaring.Location {
	if m != nil {
		return m.PeerSet
	}
	return nil
}

type RPCResponse struct {
	Entry *Entry `protobuf:"bytes,1,opt,name=Entry,json=entry" json:"Entry,omitempty"`
}

func (m *RPCResponse) Reset()                    { *m = RPCResponse{} }
func (m *RPCResponse) String() string            { return proto.CompactTextString(m) }
func (*RPCResponse) ProtoMessage()               {}
func (*RPCResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RPCResponse) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func init() {
	proto.RegisterType((*Entry)(nil), "hexalog.Entry")
	proto.RegisterType((*RPCRequest)(nil), "hexalog.RPCRequest")
	proto.RegisterType((*RequestOptions)(nil), "hexalog.RequestOptions")
	proto.RegisterType((*RPCResponse)(nil), "hexalog.RPCResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HexalogRPC service

type HexalogRPCClient interface {
	ProposeRPC(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error)
	CommitRPC(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error)
	GetRPC(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error)
	TransferKeylogRPC(ctx context.Context, opts ...grpc.CallOption) (HexalogRPC_TransferKeylogRPCClient, error)
	FetchKeylogRPC(ctx context.Context, opts ...grpc.CallOption) (HexalogRPC_FetchKeylogRPCClient, error)
}

type hexalogRPCClient struct {
	cc *grpc.ClientConn
}

func NewHexalogRPCClient(cc *grpc.ClientConn) HexalogRPCClient {
	return &hexalogRPCClient{cc}
}

func (c *hexalogRPCClient) ProposeRPC(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error) {
	out := new(RPCResponse)
	err := grpc.Invoke(ctx, "/hexalog.HexalogRPC/ProposeRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexalogRPCClient) CommitRPC(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error) {
	out := new(RPCResponse)
	err := grpc.Invoke(ctx, "/hexalog.HexalogRPC/CommitRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexalogRPCClient) GetRPC(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error) {
	out := new(RPCResponse)
	err := grpc.Invoke(ctx, "/hexalog.HexalogRPC/GetRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hexalogRPCClient) TransferKeylogRPC(ctx context.Context, opts ...grpc.CallOption) (HexalogRPC_TransferKeylogRPCClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_HexalogRPC_serviceDesc.Streams[0], c.cc, "/hexalog.HexalogRPC/TransferKeylogRPC", opts...)
	if err != nil {
		return nil, err
	}
	x := &hexalogRPCTransferKeylogRPCClient{stream}
	return x, nil
}

type HexalogRPC_TransferKeylogRPCClient interface {
	Send(*RPCRequest) error
	Recv() (*RPCRequest, error)
	grpc.ClientStream
}

type hexalogRPCTransferKeylogRPCClient struct {
	grpc.ClientStream
}

func (x *hexalogRPCTransferKeylogRPCClient) Send(m *RPCRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hexalogRPCTransferKeylogRPCClient) Recv() (*RPCRequest, error) {
	m := new(RPCRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hexalogRPCClient) FetchKeylogRPC(ctx context.Context, opts ...grpc.CallOption) (HexalogRPC_FetchKeylogRPCClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_HexalogRPC_serviceDesc.Streams[1], c.cc, "/hexalog.HexalogRPC/FetchKeylogRPC", opts...)
	if err != nil {
		return nil, err
	}
	x := &hexalogRPCFetchKeylogRPCClient{stream}
	return x, nil
}

type HexalogRPC_FetchKeylogRPCClient interface {
	Send(*RPCRequest) error
	Recv() (*RPCRequest, error)
	grpc.ClientStream
}

type hexalogRPCFetchKeylogRPCClient struct {
	grpc.ClientStream
}

func (x *hexalogRPCFetchKeylogRPCClient) Send(m *RPCRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hexalogRPCFetchKeylogRPCClient) Recv() (*RPCRequest, error) {
	m := new(RPCRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for HexalogRPC service

type HexalogRPCServer interface {
	ProposeRPC(context.Context, *RPCRequest) (*RPCResponse, error)
	CommitRPC(context.Context, *RPCRequest) (*RPCResponse, error)
	GetRPC(context.Context, *RPCRequest) (*RPCResponse, error)
	TransferKeylogRPC(HexalogRPC_TransferKeylogRPCServer) error
	FetchKeylogRPC(HexalogRPC_FetchKeylogRPCServer) error
}

func RegisterHexalogRPCServer(s *grpc.Server, srv HexalogRPCServer) {
	s.RegisterService(&_HexalogRPC_serviceDesc, srv)
}

func _HexalogRPC_ProposeRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexalogRPCServer).ProposeRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hexalog.HexalogRPC/ProposeRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexalogRPCServer).ProposeRPC(ctx, req.(*RPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexalogRPC_CommitRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexalogRPCServer).CommitRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hexalog.HexalogRPC/CommitRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexalogRPCServer).CommitRPC(ctx, req.(*RPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexalogRPC_GetRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HexalogRPCServer).GetRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hexalog.HexalogRPC/GetRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HexalogRPCServer).GetRPC(ctx, req.(*RPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HexalogRPC_TransferKeylogRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HexalogRPCServer).TransferKeylogRPC(&hexalogRPCTransferKeylogRPCServer{stream})
}

type HexalogRPC_TransferKeylogRPCServer interface {
	Send(*RPCRequest) error
	Recv() (*RPCRequest, error)
	grpc.ServerStream
}

type hexalogRPCTransferKeylogRPCServer struct {
	grpc.ServerStream
}

func (x *hexalogRPCTransferKeylogRPCServer) Send(m *RPCRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hexalogRPCTransferKeylogRPCServer) Recv() (*RPCRequest, error) {
	m := new(RPCRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HexalogRPC_FetchKeylogRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HexalogRPCServer).FetchKeylogRPC(&hexalogRPCFetchKeylogRPCServer{stream})
}

type HexalogRPC_FetchKeylogRPCServer interface {
	Send(*RPCRequest) error
	Recv() (*RPCRequest, error)
	grpc.ServerStream
}

type hexalogRPCFetchKeylogRPCServer struct {
	grpc.ServerStream
}

func (x *hexalogRPCFetchKeylogRPCServer) Send(m *RPCRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hexalogRPCFetchKeylogRPCServer) Recv() (*RPCRequest, error) {
	m := new(RPCRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _HexalogRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hexalog.HexalogRPC",
	HandlerType: (*HexalogRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposeRPC",
			Handler:    _HexalogRPC_ProposeRPC_Handler,
		},
		{
			MethodName: "CommitRPC",
			Handler:    _HexalogRPC_CommitRPC_Handler,
		},
		{
			MethodName: "GetRPC",
			Handler:    _HexalogRPC_GetRPC_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferKeylogRPC",
			Handler:       _HexalogRPC_TransferKeylogRPC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "FetchKeylogRPC",
			Handler:       _HexalogRPC_FetchKeylogRPC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x6f, 0x6b, 0xd5, 0x30,
	0x14, 0xc6, 0xd7, 0xde, 0x3f, 0x5d, 0x4f, 0xb5, 0x68, 0x14, 0x2d, 0x17, 0x5f, 0x94, 0xe2, 0x8b,
	0x82, 0xd2, 0x69, 0x87, 0xa0, 0xef, 0x84, 0x5e, 0x75, 0x63, 0x82, 0x25, 0xdb, 0x07, 0x30, 0xb7,
	0x3b, 0xb6, 0x61, 0x6b, 0x13, 0x93, 0x54, 0xd6, 0x57, 0x7e, 0x34, 0xbf, 0x9a, 0xdc, 0xb4, 0xdb,
	0x65, 0x30, 0x84, 0xf9, 0x2e, 0xe7, 0x77, 0x72, 0x9e, 0xf3, 0x3c, 0x21, 0xe0, 0x2b, 0x59, 0x65,
	0x52, 0x09, 0x23, 0x88, 0xd7, 0xe0, 0x15, 0xbb, 0x14, 0xf5, 0xea, 0x55, 0xcd, 0x4d, 0xd3, 0x6f,
	0xb2, 0x4a, 0xb4, 0x07, 0x5b, 0xb6, 0xb9, 0x14, 0xd5, 0x85, 0x3d, 0x29, 0xde, 0xd5, 0x07, 0xda,
	0xa8, 0xbe, 0x32, 0x7a, 0x9c, 0x4a, 0x7e, 0xc3, 0xe2, 0x53, 0x67, 0xd4, 0x40, 0x56, 0xb0, 0x5f,
	0x2a, 0xfc, 0xc5, 0x45, 0xaf, 0x23, 0x27, 0x76, 0xd2, 0x07, 0x74, 0x5f, 0x4e, 0x35, 0x79, 0x01,
	0xfe, 0x19, 0x6f, 0x51, 0x1b, 0xd6, 0xca, 0xc8, 0x8d, 0x9d, 0x74, 0x4e, 0x7d, 0x73, 0x0d, 0xc8,
	0x33, 0x58, 0x1e, 0x21, 0xaf, 0x1b, 0x13, 0xcd, 0x62, 0x27, 0x7d, 0x48, 0x97, 0x8d, 0xad, 0xc8,
	0x23, 0x98, 0x9d, 0xe0, 0x10, 0xcd, 0xad, 0xd8, 0xec, 0x02, 0x07, 0x42, 0x60, 0xbe, 0x66, 0x86,
	0x45, 0x0b, 0x8b, 0xe6, 0xe7, 0xcc, 0xb0, 0xa4, 0x07, 0xa0, 0x65, 0x41, 0xf1, 0x67, 0x8f, 0xda,
	0x90, 0x10, 0xdc, 0xe3, 0xf5, 0xb4, 0xdf, 0xe5, 0x6b, 0xf2, 0x72, 0xb2, 0x67, 0xb7, 0x06, 0x79,
	0x98, 0x4d, 0x21, 0x33, 0x4b, 0xe9, 0x02, 0xad, 0xf7, 0xb7, 0xe0, 0x7d, 0x93, 0x86, 0x8b, 0x4e,
	0x5b, 0x0b, 0x41, 0xfe, 0xfc, 0xe6, 0xde, 0x24, 0x3c, 0xb5, 0xa9, 0x27, 0xc6, 0x43, 0xf2, 0x1d,
	0xc2, 0xdb, 0x2d, 0x12, 0x43, 0x70, 0x2a, 0x7a, 0x55, 0xe1, 0x71, 0x77, 0x8e, 0x57, 0xd6, 0xc3,
	0x82, 0x06, 0x7a, 0x87, 0xc8, 0x6b, 0xf0, 0x4a, 0x44, 0x75, 0x8a, 0x26, 0x72, 0xe3, 0x59, 0x1a,
	0xe4, 0x24, 0xbb, 0x7e, 0xd5, 0xec, 0xab, 0xa8, 0xd8, 0x56, 0x87, 0x7a, 0x72, 0xbc, 0x92, 0x1c,
	0x42, 0x60, 0x83, 0x69, 0x29, 0x3a, 0x8d, 0xbb, 0x24, 0xce, 0x3f, 0x92, 0xe4, 0x7f, 0x5c, 0x80,
	0xa3, 0xb1, 0x41, 0xcb, 0x82, 0x7c, 0x00, 0x28, 0x95, 0x90, 0x42, 0xe3, 0xb6, 0x7a, 0xb2, 0x4b,
	0x75, 0xf3, 0x62, 0xab, 0xa7, 0xb7, 0xe1, 0xb8, 0x2d, 0xd9, 0x23, 0xef, 0xc1, 0x2f, 0x44, 0xdb,
	0x72, 0x73, 0xef, 0xc9, 0x77, 0xb0, 0xfc, 0x82, 0xf7, 0x1f, 0x2b, 0xe0, 0xf1, 0x99, 0x62, 0x9d,
	0xfe, 0x81, 0xea, 0x04, 0x87, 0x29, 0xc0, 0x9d, 0x0a, 0x77, 0xc1, 0x64, 0x2f, 0x75, 0xde, 0x38,
	0xe4, 0x23, 0x84, 0x9f, 0xd1, 0x54, 0xcd, 0x7f, 0x2b, 0x6c, 0x96, 0xf6, 0x5f, 0x1f, 0xfe, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x78, 0x0b, 0xc0, 0x37, 0x1a, 0x03, 0x00, 0x00,
}
